// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 0
  }, function(rs) {
    var rebuildObj;
    rebuildObj = {
      imageRef: '1eb491c1-c5fb-4b34-be53-196a0c0588ba',
      flavorRef: '5'
    };
    return rs.servers.assume('8347e953-c865-4742-b0a8-96f2903a89cf').rebuild(rebuildObj, function(reply) {
      return console.log(reply);
    });
  });

}).call(this);
