// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 5
  }, function(rs) {
    return rs.nextgen.servers.all(function(servers) {
      var server, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = servers.length; _i < _len; _i++) {
        server = servers[_i];
        _results.push((function() {
          var my;
          my = server;
          my.metadata(function(metadata) {
            return console.log(my.name, metadata);
          });
          return my.details(function(details) {
            return console.log(my.name, details);
          });
        })());
      }
      return _results;
    });
  });

}).call(this);
