// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 5
  }, function(rs) {
    return rs.cloudDNS.domains["new"]([
      {
        "name": "somemadeupdomaindotcomlol.com",
        "emailAddress": "fake@somemadeupdomaindotcomlol.com",
        "ttl": 3600
      }
    ], function(reply) {
      return console.log(reply);
    });
  });

}).call(this);
