// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 1
  }, function(rs) {
    return rs.servers.assume('66ac13a6-cea2-401e-98ef-bede09f35e6b').details(function(reply) {
      return console.log(reply);
    });
  });

}).call(this);
