// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 0
  }, function(rs) {
    return rs.servers.all(function(reply) {
      return reply[0].details(function(details) {
        return console.log(details);
      });
    });
  });

}).call(this);
