// Generated by CoffeeScript 1.7.1
(function() {
  var RacksJS;

  RacksJS = require('../lib/racks.js');

  new RacksJS({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 0
  }, function(rs) {
    return rs.servers.assume('ac860acc-b4bf-40f1-9eb6-64acaac5a65c').setMetadata({
      'rax_service_level_automation': 'Complete'
    });
  });

}).call(this);
